require (e.g., using deduction, persuasion,), not all social games are wargames.Creative wargames often require deception, but that is  primary; it is instead a method for reaching that goal. @sun_art_1910 = Appendix A: On Economics and Finance in Wargames <app:econ_finance>

== Economics and Finance
Wargames can be powerful tools for modeling and studying economics and finance. Games such as *Civilization IV* provide synthetic environments that mirror the fundamental structures of economic systems. They require players to allocate scarce resources (e.g., iron, oil, luxury goods), manage cities, and balance immediate needs against long-term growth, with each decision embodying core economic concepts. For example, choosing to build infrastructure instead of military units is a direct trade-off, forcing players to weigh opportunity costs. Likewise, deficit spending incurs penalties like unit disbandment, simulating bankruptcy risk and the consequences of poor financial planning. Unlike abstract models, these wargames simulate emergent market behaviors through the interactions of human and AI agents, making them valuable laboratories for applied economics.

Finance, too, is inherently adversarial. Wargames replicate these dynamics through embedded markets and trade routes where players can negotiate resource-for-gold deals. In *Civilization IV*, for instance, players can leverage comparative advantage and specialization, focusing cities on generating food, production (hammers), or commerce (gold) to create micro-economies. Deploying AI agents in such settings allows researchers to observe strategies of collusion or predatory expansion, creating an experimental platform for studying algorithmic pricing, market shocks, and competitive equilibria without real-world risk.

Other games, such as *Settlers of Catan*, provide macro-scale models of cooperation and conflict. In Catan, players act as economic agents who must trade and negotiate to succeed. This interplay mirrors real-world markets where competition and collaboration coexist. The game’s uncertainty, driven by dice rolls and development cards, forces adaptive decision-making and risk assessment under partial observability—core challenges in modern economics. Negotiation is central, involving offers, counteroffers, and persuasion, making Catan an effective testbed for AI agents. Research shows that evaluation in such games must go beyond win rates to include diversity of behavior and the discovery of emergent strategies @alabdulkarim_goal-directed_2021, which is vital for both game balancing and for generating actionable policy insights.

Through experimentation in these wargames, the fields of economics and finance can move beyond static models toward dynamic environments. By studying AI agents acting as firms, governments, or traders, researchers gain novel methodologies for testing economic theory, exploring systemic risks, and understanding strategic behavior, providing insights for the design and regulation of real-world markets.