// ===== Table of Selected AI in Wargames Papers =====

== Table of Selected AI in Wargames Papers

// Page and text formatting for compact table
#set page(margin: 0.5cm)
#set text(size: 5.5pt, hyphenate: false)
#set par(justify: false)

#table(
  columns: (15cm, 1cm, 0.7cm, 0.5cm, 0.5cm, 0.5cm),
  align: (left, center, center, center, center, center),
  stroke: 0.3pt + gray,
  inset: 1.5pt,

  // Header
  [*Paper Title*],
  [*Year*],
  [*Link*],
  [*Q*],
  [*P*],
  [*A*],

  [Adaptive Command: Real-Time Policy Adjustment via Language Models in StarCraft II],
  [2025],
  [✓],
  [I],
  [L],
  [L],

  [Exploration of Wargaming and AI Applications in Military Decision-Making],
  [2025],
  [—],
  [I],
  [L],
  [L],

  [Game Reasoning Arena: A Framework and Benchmark for Assessing Reasoning Capabilites of Large Language Models via Game Play],
  [2025],
  [✓],
  [I],
  [L],
  [L],

  [Leveraging Generative AI to Create Lightweight Simulations for Far-Future Autonomous Teammates],
  [2025],
  [✓],
  [I],
  [L],
  [L],

  [SC2Arena and StarEvolve: Benchmark and Self-Improvement Framework for LLMs in Complex Decision-Making Tasks],
  [2025],
  [✓],
  [I],
  [L],
  [L],

  [Strategy-Augmented Planning for Large Language Models via Opponent Exploitation],
  [2025],
  [✓],
  [I],
  [L],
  [L],

  [Tracing LLM Reasoning Processes with Strategic Games: A Framework for Planning, Revision, and Resource-Constrained Decision Making],
  [2025],
  [✓],
  [I],
  [L],
  [L],

  [A Land-Based War-Gaming Simulation Method Based on Multi-Agent Proximal Policy Optimization],
  [2024],
  [—],
  [I],
  [L],
  [L],

  [BALROG: Benchmarking Agentic LLM and VLM Reasoning On Games],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [BattleAgentBench: A Benchmark for Evaluating Cooperation and Competition Capabilities of Language Models in Multi-Agent Systems],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [Can Large Language Models Play Games? A Case Study of A Self-Play Approach],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [CivRealm: A Learning and Reasoning Odyssey in Civilization for Decision-Making Agents],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [Game Theory Approach to Identifying Deception in Large Language Models],
  [2024],
  [—],
  [I],
  [L],
  [L],

  [Game-Theoretic LLM: Agent Workflow for Negotiation Games],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [GameBench: Evaluating Strategic Reasoning Abilities of LLM Agents],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [Harnessing Language for Coordination: A Framework and Benchmark for LLM-Driven Multi-Agent Control],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [Maia-2: A Unified Model for Human-AI Alignment in Chess],
  [2024],
  [—],
  [I],
  [L],
  [L],

  [Mastering the Digital Art of War: Developing Intelligent Combat Simulation Agents for Wargaming Using Hierarchical Reinforcement Learning],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [PokeLLMon: A Human-Parity Agent for Pokemon Battles with Large Language Models],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [Project Sid: Many-agent simulations toward AI civilization],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [SC-Phi2: A Fine-tuned Small Language Model for StarCraft II Macromanagement Tasks],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [Shall We Team Up: Exploring Spontaneous Cooperation of Competing LLM Agents],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [Strategic behavior of large language models and the role of game structure versus contextual framing],
  [2024],
  [—],
  [I],
  [L],
  [L],

  [SwarmBrain: Embodied agent for real‑time strategy game StarCraft II via large language models.],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [The Automated but Risky Game: Modeling Agent-to-Agent Negotiations and Transactions in Consumer Markets],
  [2024],
  [✓],
  [I],
  [L],
  [L],

  [ChessGPT: Bridging Policy Learning and Language Modeling],
  [2023],
  [✓],
  [I],
  [L],
  [L],

  [Diversifying AI: Towards Creative Chess with AlphaZero],
  [2023],
  [—],
  [I],
  [L],
  [L],

  [LLM-Based Agent Society Investigation: Collaboration and Confrontation in Avalon Gameplay],
  [2023],
  [✓],
  [I],
  [L],
  [L],

  [Large Language Models Play StarCraft II: Benchmarks and A Chain of Summarization Approach],
  [2023],
  [✓],
  [I],
  [L],
  [L],

  [Large Language Models on the Chessboard: A Study on ChatGPT's Formal Language Comprehension and Complex Reasoning Skills],
  [2023],
  [✓],
  [I],
  [L],
  [L],

  [Playing Games With GPT: What Can We Learn About a Large Language Model From Canonical Strategic Games?],
  [2023],
  [✓],
  [I],
  [L],
  [L],

  [Research on Wargame Decision-Making Method Based on Multi-Agent Deep Deterministic Policy Gradient],
  [2023],
  [✓],
  [I],
  [L],
  [L],

  [Self Generated Wargame AI: Double Layer Agent Task Planning Based on Large Language Model],
  [2023],
  [✓],
  [I],
  [L],
  [L],

  [Welfare Diplomacy: Benchmarking Language Model Cooperation],
  [2023],
  [✓],
  [I],
  [L],
  [L],

  [Ares: A System-Oriented Wargame Framework for Adversarial ML],
  [2022],
  [✓],
  [I],
  [L],
  [L],

  [Mastering the Game of No-Press Diplomacy via Human-Regularized Reinforcement Learning and Planning],
  [2022],
  [✓],
  [I],
  [L],
  [L],

  [Mastering the Game of Stratego with Model-Free Multiagent Reinforcement Learning],
  [2022],
  [✓],
  [I],
  [L],
  [L],

  [Chess AI: Competing Paradigms for Machine Intelligence],
  [2021],
  [—],
  [I],
  [L],
  [L],

  [Hierarchical control of multi-agent reinforcement learning team in real-time strategy (RTS) games],
  [2021],
  [✓],
  [I],
  [L],
  [L],

  [The Surprising Effectiveness of PPO in Cooperative Multi-Agent Games],
  [2021],
  [✓],
  [I],
  [L],
  [L],

  [Learning to Play No-Press Diplomacy with Best Response Policy Iteration],
  [2020],
  [✓],
  [I],
  [L],
  [L],

  [No Press Diplomacy: Modeling Multi-Agent Gameplay],
  [2020],
  [✓],
  [I],
  [L],
  [L],

  [Playing a Strategy Game with Knowledge-Based Reinforcement Learning],
  [2020],
  [✓],
  [I],
  [L],
  [L],

  [BattleAgent: Multi-modal Dynamic Emulation on Historical Battles to Complement Historical Analysis],
  [2024],
  [✓],
  [II],
  [L],
  [L],

  [Escalation Risks from Language Models in Military and Diplomatic Decision-Making],
  [2024],
  [✓],
  [II],
  [H],
  [L],

  [War and Peace (WarAgent): Large Language Model-based Multi-Agent Simulation of World Wars],
  [2023],
  [✓],
  [II],
  [H],
  [L],

  [Experimental wargames to address the complexity: scarcity gap],
  [2020],
  [✓],
  [II],
  [L],
  [H],

  [Advancing AI Negotiations: New Theory and Evidence from an International AI Negotiation Competition],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Agent Exchange: Shaping the Future of AI Agent Economics],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Agents of Change: Self-Evolving LLM Agents for Strategic Planning],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [DSGBench: A Diverse Strategic Game Benchmark for Evaluating LLM-based Agents in Complex Decision-Making Environments],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Debt Collection Negotiations with Large Language Models],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Democratizing Diplomacy: A Harness for Evaluating Any Large Language Model on Full-Press Diplomacy],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Digital Player: Evaluating Large Language Models based Human-like Agent in Games],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Evaluating LLM Agent Collusion in Double Auctions],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [FishBargain: An LLM-Empowered Bargaining Agent for Online Flea-Market Platform Sellers],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [HARBOR: Exploring Persona Dynamics in Multi-Agent Competition],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Learning from Synthetic Labs: Language Models as Experimental Subjects in Auctions],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [MultiMind: Enhancing Werewolf Agents with Multimodal Memory],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Playing repeated games with large language models],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [SPIN-Bench:  How Well Do LLMs Plan Strategically and Reason Socially?],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Should I Trust You? Detecting Deception in Negotiations using Counterfactual RL],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [Super-additive Cooperation in Language Model Agents],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [The Traitors: Deception and Trust in Multi-Agent Language Systems],
  [2025],
  [✓],
  [III],
  [H],
  [L],

  [AMONGAGENTS: Evaluating Large Language Models in the Interactive Text-Based Social Deduction Game],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [Battlefield information and tactics engine (BITE): a multimodal large language model approach for battlespace management],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [Collaboration and Confrontation in Avalon Gameplay],
  [2024],
  [—],
  [III],
  [H],
  [L],

  [EAI: Emotional Decision-Making of LLMs in Strategic Games and Ethical Dilemmas],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [Finding deceivers in social context with large language models: the case of the Mafia game],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [Human vs. Machine: Behavioral Differences Between Expert Humans and Language Models in Wargame Simulations],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [LLMs of Catan: Exploring Pragmatic Capabilities of Generative Chatbots],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [Measuring Free-Form Decision-Making Inconsistency of Language Models in Military Crisis Simulations],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [Microscopic Analysis on LLM Players via Social Deduction Game],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [More Victories, Less Cooperation: Assessing Cicero's Diplomacy Play],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [Richelieu: Self-Evolving LLM-Based Agents for AI Diplomacy],
  [2024],
  [✓],
  [III],
  [H],
  [L],

  [AvalonBench: Evaluating LLMs Playing the Game of Avalon],
  [2023],
  [✓],
  [III],
  [H],
  [L],

  [Human-level play in the game of Diplomacy by combining language models with strategic reasoning],
  [2023],
  [—],
  [III],
  [H],
  [L],

  [It Takes Two to Negotiate: Modeling Social Exchange in Online Multiplayer Games],
  [2023],
  [✓],
  [III],
  [H],
  [L],

  [Dungeons and Dragons as a Dialogue Challenge for Artificial Intelligence],
  [2022],
  [✓],
  [III],
  [H],
  [L],

  [Negotiation and honesty in artificial intelligence methods for the board game of Diplomacy],
  [2022],
  [✓],
  [III],
  [H],
  [L],

  [Managing Escalation in Off-the-Shelf Large Language Models],
  [2025],
  [✓],
  [IV],
  [H],
  [H],

  [When Two LLMs Debate, Both Think They'll Win],
  [2025],
  [✓],
  [IV],
  [H],
  [H],

  [Large Language Models in Wargaming: Methodology, Application, and Robustness],
  [2024],
  [—],
  [IV],
  [H],
  [H],

  [Open-Ended Wargames with Large Language Models],
  [2024],
  [✓],
  [IV],
  [H],
  [H],

  [Outwit, Outplay, Out-Generate: A Framework for Designing Strategic Generative Agents in Competitive Environments],
  [2024],
  [✓],
  [IV],
  [H],
  [H],

  [Scaling Laws For Scalable Oversight],
  [2024],
  [✓],
  [IV],
  [H],
  [H],

  [What if LLMs Have Different World Views: Simulating Alien Civilizations with LLM-based Agents],
  [2024],
  [✓],
  [IV],
  [H],
  [H],

  [Encouraging Divergent Thinking in Large Language Models through Multi-Agent Debate],
  [2023],
  [✓],
  [IV],
  [H],
  [H],

)

#set text(size: 10pt, hyphenate: true)
#set page(margin: auto)

*Legend:* Q = Quadrant (I-IV) | P = Player | A = Adjudicator | H = High Creativity | L = Low Creativity | ✓ = Link Available

Total papers: 88