#import "../config.typ":num_papers
#import "@preview/tracl:0.6.1": *

= Wargames <sec:wargames>
== Selected Wargame Papers
#include "tables/table_wargames.typ" 

== Domains in Wargames
This section synthesizes key design principles for developing and evaluating LM-driven agents in open-ended wargames. Drawing from our comprehensive survey, we distill a set of core methodological considerations—such as turn structure, evidence requirements, human facilitation, and adjudication protocols—that influence the validity and analytical utility of language-based strategic simulations @robinson_stride_2018. We then contextualize these principles within specific domains to provide actionable guidance for researchers.

=== Military and National Security
AI offers militaries and national security establishments several new training and planning methodologies. Multiple defense organizations are actively exploring how to use AI to provide experiential learning and establish strategic advantage through superior decision-making and judgement @black_scaling_2024. 

Because wargames offer humans a simplified mental model that allows them to abstract away particulars and navigate decision-making and analyze the results @us_naval_war_college_fundamentals_1966 @us_army_war_college_strategic_2015, they have been used in education and training, particularly in military contexts @us_naval_war_college_war_2015 @deutschland_bundeswehr_wargaming_2017 @uk_ministry_of_defense_wargaming_2017 @uk_ministry_of_defense_wargaming_2017 @croatian_military_academy_introduction_2019 @australian_armed_forces_wargaming_2022 @polish_armed_forces_wargaming_2022 @us_army_how_2023 @nato_wargaming_2023 @french_ministry_of_the_armed_forces_wargaming_2024.

We have observed how both military SMEs and academic researchers are currently investigating how LMs can be used to help AI act as players and adjudicators in open-ended wargames @black_mastering_2024 @griffin_matrix_2024. This news comes at a time when the safety-critical nature of these systems is of high importance and is receiving considerable attention. However, there is not currently a resource to help bridge the understanding gap between AI researchers and SMEs for this domain. We believe that non-military scientists and academics have a major role to play in the effectiveness and alignment of AI systems, particularly those in safety-critical settings.

Finally, we have identified several examples of opportunities to infuse LMs into new and existing wargaming activities. 
At the tactical level, wargames primarily serve as individual, small unit, and command and staff training experiences. While LMs are unlikely to take to the battlefield as an opposing force, LM wargaming software could be connected with existing battle command systems to increase staff engagement during field training exercises. 
At the operational level, staff wargaming activities (i.e., to evaluate plans) could be greatly enhanced with an LM agent playing the role of the opposing forces commander, LM agent adjudicators, and LM agents that play out branches and sequels from decision points that the human players do not explore themselves. 
This LM-powered exploration of branches and sequels provides significant value for planners at the strategic level, enabling the rapid exploration of the possible to identify the probable. Stepping up from the strategic level to grand strategic, the use of LM agents to explore plans and policy outcomes could provide significant advantages to decisionmakers compared to allies, adversaries, and other parties that perhaps do not have similar capabilities.


// [battlefield/material focused wargames vs diplomacy we can leave diplomatic aspects of military wargames to next section to avoid overlap, can mention] - isaac
// At the time of writing, numerous national military and security organizations are actively exploring how they can use AI to provide experiential learning and potentially establish a strategic advantage through superior decision-making and judgment 

==== Cybersecurity
Cybersecurity wargames encompasses a variety of wargaming activity, from hands-on-keyboard technical operations, to 

=== International Relations
International Relations (IR) wargaming centers on language, signaling, and credibility rather than material force, and is used for communication, negotiation, and diplomacy. Open‑ended, argument‑driven formats (seminar, matrix) capture how positions evolve through persuasion, norm invocation, and threat–promise exchanges across multiple stakeholders (e.g., national states, non-government or industrial organizations) @mans_training_2010 @schechter_wargaming_2021 @lin-greenberg_wargaming_2022. When LMs participate, their value is in maintaining coherent narratives over long horizons, proposing plausible options under contested facts, helping surface implicit assumptions in briefs and communiqués, processing scenarios, and aiding with adjudication on non-analytical rubrics and procedures.
In a similar manner to how wargames are used extensively by the officer corps of a military, wargames are commonplace among IR professionals. Wargames present an opportunity for experiential learning for diplomatic training. Wargames are used both to support training and development, and to analyze and gain a deeper understanding of diplomatic crises that were previously unseen or extremely infrequent (i.e., nuclear crises). @hersman_under_2020 @lin-greenberg_wargaming_2022 @reddie_evidence_2023 @worman_designing_2023

Compared with military applications, diplomatic games emphasize incomplete and asymmetric information, face‑saving, issue linkage (security tied to trade, technology, or climate), and a shift away from material forces towards abstracted interests. Facilitation and adjudication must account for audience costs, domestic politics, and path dependence across rounds. LMs can assist by drafting position papers, back‑channel messages, or press releases in different registers, while humans retain control of red lines, escalation ladders, and legitimacy constraints.
Practical design choices that matter include: clear turn structure (front‑channel vs. back‑channel), explicit rules for information sharing and leaks, and rubrics that reward consistency and coalition‑building rather than only “wins.” Artifact capture (transcripts, proposals, dissent notes) is crucial for after‑action learning. Reproducibility improves when scenarios, prompts, and adjudication criteria are shared alongside model/version information.
IR professionals in particular benefit from wargaming because of its creative and non-analytical structure. With subjective rubrics and emphasis on cooperation and social interactions, innovative players and adjudications are nearly necessary and alleviate human cost from traditional executions of diplomatic wargames with human players and computers, whether it is through fully autonomous or human-aided.

=== Social Games
While wargames may contain elements of social reasoning or deception, they differ fundamentally from social deduction games in that deception is not the objective but a component of broader strategic reasoning. Wargames require agents to pursue defined goals through planning and decision-making within a structured conflict environment. In contrast, social deduction games are centered around identity discovery and psychological misdirection, making them categorically distinct. This distinction is critical for evaluating LMs in open-ended scenarios, as social deduction games test their ability to navigate dynamic, multi-agent interactions involving trust and deception @chi_amongagents_2024.

Psychological misdirection is prolific in warfare, however, and history is rife with examples of cunning tacticians using it with great success. As the Chinese military strategist Sun Tzu famously wrote, _"All warfare is based on deception,"_ exemplified by tactics like the Trojan Horse, the Empty Fort Strategy, and Hannibal’s crossing of the Alps to outmaneuver Roman forces through strategic diversions. For this literature review, social deduction games represent a complementary effort to wargames, as their focus on harnessing psychological misdirection in game scenarios can enhance LMs’ performance in real-life contexts where information may be unreliable, mislabeled, or intentionally deceptive @maggio_game_2024 @lamparth_human_2024. By studying LMs in these settings, researchers can improve their adaptability to ambiguous, deception‑heavy scenarios critical to both wargaming and broader AI applications.


=== Businesses and Organizations
// BUSINESS CITATIONS:
// @scherpereel_decision_2005
// @bradfield_origins_2005
// @chussil_learning_2007
// @coyne_predicting_2009
// @hamel_competing_1994
// @hershkovitz_wargame_2019
// @kurtz_business_2003
// @oliverschwarz_ex_2011
// @resende_critical_2018
// @scherpereel_changing_2005
// @scherpereel_decision_2005
// @scherpereel_impact_2003
// @schwarz_business_2013
// @schwarz_combining_2019
In business and organizational contexts, wargaming draws on competitive strategy (Porter) and scenario planning to stress‑test hypotheses under adversarial dynamics, market shifts, and policy shocks. Seminar‑style sessions often combine narrative role‑play (competitor, regulator, customer) with structured turns where teams propose moves (pricing, product launch, alliances) and facilitators adjudicate based on feasibility and consistency. Unlike fully quantitative strategy simulators, these games emphasize qualitative reasoning, internal alignment, and the articulation of assumptions.
When LMs participate, their chief value is speed and breadth in ideation (enumerating strategic options), drafting memos or internal communications in given styles, and probing counterfactuals (“what would a rational competitor do if…”). However, ungrounded extrapolations are a risk; prompts must enforce evidence requirements: claims must cite assumptions, external signals, or benchmarks @wheaton_making_2020. Adjudication blends simple quantitative checks (unit economics, capacity) with narrative plausibility. LMs can draft memos, scenario briefs, or stakeholder analyses conditioned on constraints (budget, brand voice, compliance) and can help enumerate second‑order effects, but human facilitators keep realism and ethics in scope.

For organizational adoption, reproducibility and governance are key. Keep minimal artifacts (scenario text, prompts, seeds, facilitation script), log model/version and any tool use (RAG, calculators), and separate confidential data from public scaffolds. Typical evaluation rubrics emphasize clarity of reasoning, sensitivity analysis (what if X changes), and decision traceability. Sharing sanitized transcripts and prompt scaffolds accelerates reuse across teams while protecting proprietary details.

=== Economics and Finance
Wargames can be powerful tools for modeling and studying economics and finance. Games such as Civilization IV provide synthetic environments that mirror the fundamental structures of economic systems, requiring players to allocate resources, manage cities, and balance immediate needs against long-term growth. Each decision embodies core economic concepts—opportunity cost, inflation, deficit spending—where constraints shape strategy and outcomes. Unlike abstract models, wargames simulate emergent market behaviors through the interactions of both human players and AI agents. This makes them valuable laboratories for applied economics, enabling researchers to test economic theories under controlled yet dynamic conditions.

Finance, too, is inherently adversarial and strategic: firms compete for market share, governments set monetary policy, and traders react to limited information. Wargames replicate these dynamics through embedded markets, trade routes, and investment decisions, where each choice has lasting consequences. In Civilization IV, for example, controlling strategic resources functions like commodity market dominance, while trade agreements resemble bilateral contracts. Deploying AI agents in such settings allows economics and finance researchers to observe strategies of collusion, innovation, and predatory expansion under dynamic conditions. This creates an experimental platform for studying algorithmic pricing, market shocks, and competitive equilibria without real-world risk.

Other games, such as Settlers of Catan, also provide valuable macro-scale models of cooperation, conflict, and uncertainty. In Catan, players act as economic agents competing to expand while relying on negotiation and trade to succeed. This interplay mirrors real-world markets where competition and collaboration coexist. Uncertainty introduced by dice rolls and development cards forces adaptive decision-making, risk assessment, and learning under partial observability—core challenges in modern economic and policy processes. Negotiation, bluffing, and persuasion make Catan especially relevant as a testbed for AI agents, encouraging the study of advanced dialogue, bargaining tactics, and emergent strategic behaviors.

Through experimentation with AI in wargames, the fields of economics and finance can move beyond static theoretical models toward dynamic environments governed by uncertainty and enforced by structured adjudicators. AI agents acting as firms, governments, or traders enable exploration of systemic risks, policy interventions, and resource distribution at scale. By studying these agents in wargames such as Civilization IV and Settlers of Catan, researchers gain novel methodologies for testing, refining, and even challenging economic and financial theory. In doing so, wargames not only deepen our understanding of strategic behavior but also provide actionable insights into the design and regulation of real-world markets.

=== Medicine and Public Health
Wargaming is not limited to military and geopolitical conflicts. It has also been used to great effect in the fields of medicine and public health to prepare for and respond to health crises. A prominent example is the "Dark Winter" exercise, a 2001 simulation of a smallpox attack on the United States, which highlighted critical deficiencies in the nation's preparedness for a bioterrorist attack.

Following the precedent of "Dark Winter", numerous other wargames and simulation exercises have been conducted to address a variety of public health challenges. These exercises, often referred to as tabletop exercises (TTXs) or drills, are crucial tools for testing emergency plans, training personnel, and improving coordination between different agencies. For instance, "Event 201" simulated a global pandemic to identify and address the economic and societal challenges it would pose. These simulations have proven invaluable in preparing for real-world events like the COVID-19 pandemic, allowing policymakers and healthcare professionals to rehearse their responses in a controlled environment @smith_serious_2020.


== Economics and Finance Games

=== Resource Economy
One of the most fundamental concepts in why economics is studied comes from the fact of resource scarcity. The game itself provides limited access to scarce resources such as iron, oil, uranium as well as luxury goods such as gold, spices, and gems. Due to the fact that there are multiple players, this inherently causes competition, another economic concept which is the basis for economical decision making in the game.

=== Markets and Trade
This section dives into the idea of comparative advantage and market dynamics. Cities can establish trade routes domestically and internationally in which players can negotiate resource-for-gold trades and technology exchanges. The pure concept of trading incorporates the idea of comparative advantage. Each player has their own set of resources and goods, but the way in which they choose to trade comes from the production from the cities they own in _Civilization_. Comparative advantage is a fundamental concept in economics which governs how countries, or in this case civilizations, will trade with one another. In addition, the concept of specialization can be seen taking place in this game. Each city can either generate food, produce hammers, or foster commerce with gold. Each player will ultimately have each city specializing in one field so as to create microeconomic dynamics with other cities and inherently lead to trade with other cities. These fundamental economic concepts need to be handled appropriately by a player so as to maximize personal economic benefit, which can in turn lead to better gameplay and a higher likelihood of winning.

=== Currency Taxation
In this game, budget constraints and bankruptcy risks are added as another obstacle. Deficit spending in the game has penalties such as unit disbanding and cutting science and culture. These rules simulate the business world in the sense that with greater power comes greater responsibility. The larger the empire the higher it will cost to upkeep all factors involved, and in situations where there isn’t enough money to support the empire, pieces of the empire will be taken away. In addition to these business modelings, inflation is another factor in the game which attests to market friction, in which building a large empire also makes it harder to continue to grow the empire. It forces strategic financial planning so that an empire cannot just expand way too quickly without accounting for the empire inefficiencies or lack of balance.

=== Infrastructure
One of the biggest economic factors involved in this gameplay is opportunity cost. Each turn a player has they have a decision to make. Each user can make capital investments with delayed returns. A big opportunity cost question always comes with the building or adding of infrastructure versus aiding in military personnel. In this example, you have the choice of creating a new city and adding to your wealth comes with the opportunity cost of military readiness. Similarly, each decision made has some tradeoff or opportunity cost which can lead to future positives or future negatives. A player must weigh their options accordingly and make the decision which they think will minimize their opportunity cost, a very subjective decision.

Settlers of Catan exemplifies a macro-scale simulation of cooperation, conflict, and uncertainty, offering valuable parallels to both wargaming and global economic systems. In Catan, each player acts as an economic agent—whether a company, policymaker, or trader—competing to expand their territory and win, but also needing to collaborate through trade and negotiation. This interplay mirrors real-world dynamics, where nations and market participants must adapt, compete, and form alliances within an ever-changing economic landscape.

A defining feature of Catan is its unpredictable environment, shaped by dice rolls and development card draws, which introduces uncertainty and requires constant risk assessment. Players must dynamically adjust their strategies, learn from experience, and make decisions under partial observability, closely reflecting the complexities of modern economic and policy-making processes.
Negotiation is central to Catan, as players engage in multi-party interactions involving offers, counteroffers, acceptance, and refusal. These exchanges model real-world group decision-making and strategic communication, requiring careful analysis of opponents’ positions and negotiation tactics such as bluffing and persuasion. This makes Catan an effective testbed for AI agents, fostering their development of advanced dialogue, strategy adaptation, and even deceptive bargaining behavior.

Recent research demonstrates that AI agents trained in Catan can emulate distinct roles—trader, strategist, negotiator—each influencing and responding to the decisions of others. Findings also indicate that as agent skill increases, so does the impact of luck: highly skilled agents more effectively capitalize on favorable scenarios, further emphasizing the game’s intrinsic uncertainty.

Evaluating reinforcement learning agents in environments like Catan goes beyond win rates; it includes diversity of behavior, skill expression, and the uncovering of rare or emergent strategies @alabdulkarim_goal-directed_2021. Such diversity is vital for playtesting, balancing, and informing both AI research and game design. By shifting the focus from victory to exploration and policy testing, Catan enables a deeper understanding of agent behavior, strategic planning, and the identification of hidden exploits, offering actionable insights for both policymaking and strategic game development.

== Human-Agent Interactions (HAI) vs Agent-Agent Interactions (A2A) 
Especially in negotiation‑centric settings and highly creative agents, previous research leans toward Human–Agent Interactions (HAI) with emphasis on emulating or integrating with human diplomatic behavior. Often it is a single AI agent interacting with a group of human players, as seen typically in AI research with negotiation‑centric board games. With diplomacy and collaboration being the focus, the state of the game strongly encourages AI agents to adopt the social language of the rest of the players. Such research is often conducted through random games on online platforms with text‑based communications, and mostly without the human users being strongly informed of the presence of the AI agent on the platform, let alone that they are playing against an AI agent @meta_fundamental_ai_research_diplomacy_team_human-level_2022. The focus is often on how AI interacts compared to human diplomatic strategies as the primary benchmark, with the target of human‑like behavior, and evaluated on performance against humans. 

However, agent–agent interaction (A2A) is increasingly important as agentic AI proliferates in practice, including organizational and enterprise contexts. Conflicts between multiple agentic systems will differ from HAI dynamics. Much prior work studies cooperative tasks or MoE coordination; competitive diplomatic A2A remains sparse. Human‑likeness, a common HAI benchmark, may not translate to A2A settings with different equilibria and strategies.
